exports.seeking_elastic_dialog_map = {
   "form_id":"ksLFy7",
   "relationships":[
       {
          "dialogFlow_intentName":"SPEC_UNSTRUC---IdealTenant",
          "dialogFlow_intentID":"projects/staging-landlordai/agent/intents/60db8de3-d2b2-40a5-be2b-741a548263fd",
          "typeForm_Tags":[
            "IDEAL_TENANT"
          ]
       },
      {
         "dialogFlow_intentName":"SPEC_UNSTRUC---RequiredDocuments",
         "dialogFlow_intentID":"projects/staging-landlordai/agent/intents/a43b5fad-a475-49e5-94b9-df966326a567",
         "typeForm_Tags":[
           "SUPPORTING_DOCS"
         ]
      },
      {
         "dialogFlow_intentName":"SPEC_UNSTRUC---IncomeRequirements",
         "dialogFlow_intentID":"projects/staging-landlordai/agent/intents/b3d99e69-8c4b-4e98-8297-4655d8a744bf",
         "typeForm_Tags":[
           "INCOME_REQUIREMENTS"
         ]
      },
      {
         "dialogFlow_intentName":"SPEC_UNSTRUC---Pets",
         "dialogFlow_intentID":"projects/staging-landlordai/agent/intents/34142e54-9554-4f7f-93a5-11f0de294a57",
         "typeForm_Tags":[
           "PETS"
         ]
      }
   ]
}
